# Generated by Django 5.0.6 on 2025-06-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo_usuario',
            field=models.CharField(choices=[('Proveedor', 'Proveedor'), ('Arrendador', 'Arrendador')], default='Proveedor', max_length=50),
        ),
    ]
