# Generated by Django 5.0.6 on 2025-07-15 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=100)),
                ('codigo_verificacion', models.IntegerField()),
                ('tipo_usuario', models.CharField(max_length=50)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='proximidad_app.categoria')),
                ('proveedor', models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='proximidad_app.usuario')),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('comentario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('servicio_fk', models.ForeignKey(db_column='servicio_fk', on_delete=django.db.models.deletion.CASCADE, to='proximidad_app.servicios')),
                ('usuario_fk', models.ForeignKey(db_column='usuario_fk', on_delete=django.db.models.deletion.CASCADE, to='proximidad_app.usuario')),
            ],
            options={
                'db_table': 'comentarios',
            },
        ),
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('favorito_id', models.ForeignKey(db_column='favorito_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorito_usuario', to='proximidad_app.usuario')),
                ('usuario_id', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_favorito', to='proximidad_app.usuario')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('usuario_id', 'favorito_id')},
            },
        ),
    ]
