# Generated by Django 5.0.6 on 2025-08-26 01:51

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import proximidad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0003_servicios_activo_servicios_fecha_actualizacion_and_more'),
    ]

    operations = [
        # Solo actualizar las opciones de los modelos, no los campos
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['orden', 'nombre_categoria']},
        ),
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'ordering': ['-fecha_creacion']},
        ),
        
        # Marcar esta migración como aplicada sin cambiar la estructura de la base de datos
        migrations.RunSQL(
            "SELECT 1;",  # Comando SQL inofensivo
            reverse_sql="SELECT 1;"
        ),
    ]
