# Generated by Django 5.0.6 on 2025-09-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codigo_verificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
