# Generated by Django 5.0.6 on 2025-12-02 04:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import proximidad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0008_remove_favoritos_unique_usuario_favorito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioImagenes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=proximidad_app.models.upload_to_servicios, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=0, help_text='Orden de visualización (1-5)')),
                ('es_principal', models.BooleanField(db_index=True, default=False, help_text='Indica si es la imagen principal')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='proximidad_app.servicios')),
            ],
            options={
                'db_table': 'servicio_imagenes',
                'ordering': ['orden'],
                'indexes': [models.Index(fields=['servicio', 'orden'], name='servicio_im_servici_cfbefb_idx'), models.Index(fields=['es_principal'], name='servicio_im_es_prin_5dcf77_idx')],
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('precio_acordado', models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado entre cliente y proveedor', max_digits=10, null=True)),
                ('descripcion_personalizada', models.TextField(help_text='Descripción detallada del proyecto solicitado por el cliente')),
                ('urgencia', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10)),
                ('fecha_preferida', models.DateField(blank=True, help_text='Fecha preferida de inicio del proyecto', null=True)),
                ('presupuesto_maximo', models.DecimalField(blank=True, decimal_places=2, help_text='Presupuesto máximo del cliente', max_digits=10, null=True)),
                ('comentarios_adicionales', models.TextField(blank=True, help_text='Comentarios adicionales del cliente')),
                ('respuesta_proveedor', models.TextField(blank=True, help_text='Respuesta o propuesta del proveedor')),
                ('fecha_respuesta', models.DateTimeField(blank=True, help_text='Fecha en que el proveedor respondió', null=True)),
                ('fecha_solicitud', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, help_text='Fecha de inicio del trabajo', null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, help_text='Fecha de finalización del trabajo', null=True)),
                ('notificado_cliente', models.BooleanField(default=False, help_text='Email enviado al cliente')),
                ('notificado_proveedor', models.BooleanField(default=False, help_text='Email enviado al proveedor')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_realizadas', to='proximidad_app.usuario')),
                ('proveedor', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='proximidad_app.usuario')),
                ('servicio', models.ForeignKey(db_column='servicio_id', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='proximidad_app.servicios')),
            ],
            options={
                'db_table': 'solicitudes',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['cliente', 'estado'], name='solicitudes_cliente_ecc65c_idx'), models.Index(fields=['proveedor', 'estado'], name='solicitudes_proveed_3e6562_idx'), models.Index(fields=['servicio'], name='solicitudes_servici_13ce8e_idx'), models.Index(fields=['estado', 'fecha_solicitud'], name='solicitudes_estado_feeee2_idx'), models.Index(fields=['fecha_solicitud'], name='solicitudes_fecha_s_ec5282_idx')],
            },
        ),
    ]
