# Generated by Django 5.0.6 on 2024-12-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=100)),
                ('codigo_verificacion', models.IntegerField()),
                ('tipo_usuario', models.CharField(choices=[('proveedor', 'Proveedor'), ('arrendador', 'Arrendador')], max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proX.categoria')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proX.usuario')),
            ],
            options={
                'db_table': 'servicios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('servicio', models.ForeignKey(db_column='servicio_fk', on_delete=django.db.models.deletion.CASCADE, to='proX.servicio')),
                ('usuario', models.ForeignKey(db_column='usuario_fk', on_delete=django.db.models.deletion.CASCADE, to='proX.usuario')),
            ],
            options={
                'db_table': 'comentarios',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_favorito_de', to='proX.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='proX.usuario')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('usuario', 'favorito')},
            },
        ),
    ]
