# Generated by Django 5.0.6 on 2024-11-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=200)),
                ('cedula', models.CharField(max_length=100)),
                ('codigo_verificacion', models.IntegerField()),
                ('tipo_usuario', models.CharField(choices=[('proveedor', 'Proveedor'), ('arrendador', 'Arrendador')], max_length=50)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
