# Generated by Django 5.0.6 on 2025-01-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_fecha_generacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
