# Generated by Django 5.0.6 on 2024-12-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proX', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('descripcion_categoria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
    ]
