# Generated by Django 5.0.6 on 2024-12-05 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proX', '0002_categoria_servicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_favorito_de', to='proX.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoritos', to='proX.usuario')),
            ],
            options={
                'db_table': 'favoritos',
                'unique_together': {('usuario', 'favorito')},
            },
        ),
    ]
