services:
  frontend:
    build:
      context: ../
      dockerfile: docker/front/Dockerfile
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
