# Generated by Django 5.0.6 on 2025-09-16 01:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import proximidad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0004_auto_20250825_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='color',
            field=models.CharField(default='#007bff', help_text='Color hexadecimal', max_length=7, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(blank=True, help_text='Clase CSS del icono', max_length=50, verbose_name='Icono'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='orden',
            field=models.PositiveIntegerField(default=0, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='calificacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Calificación del 1 al 5', null=True, verbose_name='Calificación'),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='fecha_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha agregado'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='destacado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destacado'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ubicación'),
        ),
        migrations.AddField(
            model_name='servicios',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Visualizaciones'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre_categoria',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='servicio_fk',
            field=models.ForeignKey(db_column='servicio_fk', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proximidad_app.servicios'),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='usuario_fk',
            field=models.ForeignKey(db_column='usuario_fk', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_realizados', to='proximidad_app.usuario'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='proximidad_app.categoria'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fecha_creacion',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=proximidad_app.models.upload_to_servicios, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='nombre_servicio',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='precio_base',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='proveedor',
            field=models.ForeignKey(blank=True, db_column='proveedor_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_ofrecidos', to='proximidad_app.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_electronico',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=proximidad_app.models.upload_to_usuarios, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombre_completo',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['nombre_categoria'], name='categoria_nombre__e7493f_idx'),
        ),
        migrations.AddIndex(
            model_name='categoria',
            index=models.Index(fields=['activo', 'orden'], name='categoria_activo_367780_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarios',
            index=models.Index(fields=['servicio_fk'], name='comentarios_servici_318b02_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarios',
            index=models.Index(fields=['usuario_fk'], name='comentarios_usuario_bb2b0b_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarios',
            index=models.Index(fields=['fecha_creacion'], name='comentarios_fecha_c_5f2e38_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarios',
            index=models.Index(fields=['calificacion'], name='comentarios_calific_85f775_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarios',
            index=models.Index(fields=['activo'], name='comentarios_activo_799eaa_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['usuario_id'], name='favoritos_usuario_ed02b8_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['favorito_id'], name='favoritos_favorit_5f3fa2_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['fecha_agregado'], name='favoritos_fecha_a_cd1352_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['nombre_servicio'], name='servicios_nombre__242c77_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['precio_base'], name='servicios_precio__28aa9e_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['activo', 'destacado'], name='servicios_activo_b28cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['categoria', 'activo'], name='servicios_categor_398a50_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['proveedor', 'activo'], name='servicios_proveed_2c353c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['views'], name='servicios_views_94f172_idx'),
        ),
        migrations.AddIndex(
            model_name='servicios',
            index=models.Index(fields=['fecha_creacion'], name='servicios_fecha_c_77edc0_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['correo_electronico'], name='usuario_correo__eb4fac_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['cedula'], name='usuario_cedula_594ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['tipo_usuario'], name='usuario_tipo_us_8871f9_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['activo'], name='usuario_activo_2eb730_idx'),
        ),
        migrations.AddIndex(
            model_name='usuario',
            index=models.Index(fields=['fecha_registro'], name='usuario_fecha_r_67c773_idx'),
        ),
    ]
