# Generated by Django 5.0.6 on 2025-09-29 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0005_categoria_activo_categoria_color_categoria_icono_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='favoritos',
            name='favoritos_usuario_ed02b8_idx',
        ),
        migrations.RemoveIndex(
            model_name='favoritos',
            name='favoritos_favorit_5f3fa2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='favoritos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='favorito_servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorito_en', to='proximidad_app.servicios'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='favorito_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soy_favorito_de', to='proximidad_app.usuario'),
        ),
        migrations.AddField(
            model_name='favoritos',
            name='tipo_favorito',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('servicio', 'Servicio')], default='usuario', max_length=10),
        ),
        migrations.AlterField(
            model_name='favoritos',
            name='usuario_id',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='mis_favoritos', to='proximidad_app.usuario'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['usuario_id', 'tipo_favorito'], name='favoritos_usuario_347b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['favorito_usuario'], name='favoritos_favorit_f6c59e_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['favorito_servicio'], name='favoritos_favorit_400e1b_idx'),
        ),
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_favorito', 'usuario')), fields=('usuario_id', 'favorito_usuario'), name='unique_usuario_favorito'),
        ),
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo_favorito', 'servicio')), fields=('usuario_id', 'favorito_servicio'), name='unique_servicio_favorito'),
        ),
        migrations.AddConstraint(
            model_name='favoritos',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('tipo_favorito', 'usuario'), ('favorito_usuario__isnull', False), ('favorito_servicio__isnull', True)), models.Q(('tipo_favorito', 'servicio'), ('favorito_servicio__isnull', False), ('favorito_usuario__isnull', True)), _connector='OR')), name='favorito_valido'),
        ),
        migrations.RemoveField(
            model_name='favoritos',
            name='favorito_id',
        ),
    ]
