# Generated by Django 5.0.6 on 2025-10-01 00:22

import django.core.validators
import proximidad_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0006_remove_favoritos_favoritos_usuario_ed02b8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='banner',
            field=models.ImageField(blank=True, help_text='Imagen de banner para el fondo del perfil (1200x400 recomendado)', null=True, upload_to=proximidad_app.models.upload_to_usuarios, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Banner de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario (aparece en círculo)', null=True, upload_to=proximidad_app.models.upload_to_usuarios, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Foto de perfil'),
        ),
    ]
