# Generated by Django 5.0.6 on 2025-10-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0007_agregar_banner_usuario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoritos',
            name='unique_usuario_favorito',
        ),
        migrations.RemoveConstraint(
            model_name='favoritos',
            name='unique_servicio_favorito',
        ),
        migrations.RemoveConstraint(
            model_name='favoritos',
            name='favorito_valido',
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['usuario_id', 'favorito_usuario'], name='favoritos_usuario_bf0ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='favoritos',
            index=models.Index(fields=['usuario_id', 'favorito_servicio'], name='favoritos_usuario_587f8c_idx'),
        ),
    ]
