# Generated by Django 5.0.6 on 2025-12-03 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proximidad_app', '0009_servicioimagenes_solicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitud',
        ),
    ]
